spring:
      datasource:
                url: jdbc:postgresql://localhost:5432/postgres
                username: postgres
                password: postgres
                driverClassName: org.postgresql.Driver
                
      jpa:
           show-sql: true
           hibernate:
                    ddl-auto: update
           
server:
      port: 8082           
           
                    
                